version: '3'
services:
  web:
    build: ./
    ports:
      - 8000:8000
    volumes:
      - ./config/config/:/config
      - ./config/downloads/:/downloads
    environment:
      - TZ=Europe/Lisbon
#      - SENTRY_DSN=https://@.ingest.sentry.io/123
